#!/usr/bin/env make -f

#**
#* @file    drivers/makefile
#* @brief   driver makefile
#* @version 0.1
#* @date    24.05.2015.
#*
#* @author Armands Skolmeisters  (Arseniuss) <arseniuss@arseniuss.id.lv>
#* @copyright see file LICENSE
#*

include config.mk
